Week 4/concert_platform/config/routes.rb
Rails.application.routes.draw do
    root :to => "concerts#index"
    resources :concerts
    get 'concerts/:id/like', to: 'concerts#like'
end

Week 4/concert_platform/app/models/concert.rb
class Concert < ActiveRecord::Base
	validates :band_name, :venue, :city, :date, :price, :description, presence: true
end

Week 4/concert_platform/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Week 4/concert_platform/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    @concerts = Concert.all
  end
  def new
    @concert = Concert.new
  end
  def show
    @concert = Concert.find(params[:id])
  end
  def create
    @concert = Concert.new(concert_params)
    if @concert.save
      redirect_to concerts_path(@concerts)
    else
      render :new
    end
  end
  def update
    @concert = Concert.find(params[:id])
    @concert.update(concert_params)
    redirect_to  concert_path(@concert)
    end
    def destroy
      @concert = Concert.find(params[:id])
      @concert.destroy
      redirect_to root_path
    end

    private
    def concert_params
      params.require(:concert).permit(:band_name, :venue, :city, :date, :price, :description)
    end
end

Week 4/concert_platform/app/helpers/application_helper.rb
module ApplicationHelper
end

Week 4/concert_platform/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Week 4/concert_platform/app/views/concerts/edit.html.erb
<h1>Editing concert</h1>
<%= form_for :concert, url: concert_path(@concert), method: :patch do |f| %>
  <p>
    <%= f.label :band_name %><br>
    <%= f.text_field :string %>
  </p>
  <p>
    <%= f.label :venue %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :city %><br>
    <%= f.text_area :text %>
  </p>
 <p>
    <%= f.label :date %><br>
    <%= f.text_area :date %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_area :float %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', concerts_path%>

<p>
  <strong>Lugar:</strong>
  <%= @concert.venue %>
</p>
<p>
  <strong>Ciudad:</strong>
  <%= @concert.city %>
</p>
<p>
  <strong>Fecha</strong>
  <%= @concert.date %>
</p>
<p>
  <strong>Precio:</strong>
  <%= @concert.price %>
</p>
<p>
  <strong>Descripción:</strong>
  <%= @concert.description %>
</p>

<p>
    <%= link_to 'Edit', edit_concert_path(@concert)%> |
    <%= link_to 'Back', concerts_path%>
</p>

Week 4/concert_platform/app/views/concerts/index.html.erb
<div id='loDeDentro'>
<h1>Concert Platform</h1>
<% @concerts.each do |concert| %>
	<div id='especial'><strong><%= concert.band_name.rjust(5) %></strong>
	</div>
	<div id='enlaces'>
		<%= link_to 'Show',  concert_path(concert)%>
		&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbsp
        <%= link_to 'Destroy', concert_path(concert), method: :delete, data: { confirm: '¿Estás seguro, machote?' } %>
    </div>
<% end %>
    <span id='newC'><%= link_to 'New concert', new_concert_path %></span>
</div>

Week 4/concert_platform/app/views/concerts/new.html.erb
<%= form_for @concert do |f| %>
<div id='loDeDentro'>
  <p>
    <%= f.label :band_name %><br>
    <%= f.text_field :band_name %>
  </p>
  <p>
    <%= f.label :venue %><br>
    <%= f.text_area :venue %>
  </p>
  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.text_area :date %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to 'Back', concerts_path, :id => 'back' %>
</p>
</div>

Week 4/concert_platform/app/views/concerts/show.html.erb
<div id='loDeDentro'>
<p id='notice'><%= notice %></p>
<h1><%= @concert.band_name %></h1>
<p id='especial'>
	<strong>Lugar:</strong>
	<%= @concert.venue %>
	<strong>&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbspCiudad:</strong>
	<%= @concert.city %>
	<strong>&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbspFecha:</strong>
	<%= @concert.date %>
	<strong>&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbspPrecio:</strong>
	<%= @concert.price %> euros
</p>
<p id='descrip'>
	<strong>Descripción:</strong><br/>
	<%= @concert.description %>
</p>

<!--<button type='button' id='like-button'>Me gusta</button>-->
<input type='button' onClick='cuentaLikes()' Value='Me gusta' id='like-button'/>
<span id = 'result'> 0</span> likes

<%= link_to 'Back', concerts_path, :id => 'back' %>
</div>

Week 4/concert_platform/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertPlatform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>