Week 2/ordenador/config/routes.rb
Rails.application.routes.draw do
  root :to => "articles#index"
  resources :articles
  resources :backpacks



end

Week 2/ordenador/app/models/article.rb
class Article < ActiveRecord::Base
end

Week 2/ordenador/app/models/backpack.rb
class Backpack < ActiveRecord::Base
end

Week 2/ordenador/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
   @article = Article.new
    end

    def edit
  @article = Article.find(params[:id])
end

    def create
        @article = Article.new(article_params)
        @article.save
        redirect_to article_path(@article)
    end
    def update
  @article = Article.find(params[:id])
  @article.update(article_params)
  redirect_to  article_path(@article)
end
def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to root_path
end

    private
    def article_params
        params.require(:article).permit(:title,:Modelo, :Procesador, :RAM, :Precio)
    end
end

Week 2/ordenador/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
	  def index
        @backpacks = Backpack.all
      end
      def show
        @backpack = Backpack.find(params[:id])
      end
      def new
   @backpack = Backpack.new
    end
def edit
  @article = Backpack.find(params[:id])
end
    def create
        @backpack = Backpack.new(backpack_params)
        @backpack.save
        redirect_to backpack_path(@backpack)
    end

    def update
  @backpack = Backpack.find(params[:id])
  @backpack.update(backpack_params)
  redirect_to  backpack_path(@backpack)
end

def destroy
  @backpack = Backpack.find(params[:id])
  @backpack.destroy

  redirect_to root_path
end

    private
    def backpack_params
        params.require(:backpack).permit(:title,:Color,:Capacidad,:Bolsillos,:Resistente)
    end
  end

Week 2/ordenador/app/helpers/articles_helper.rb
module ArticlesHelper
end

Week 2/ordenador/app/helpers/backpack_helper.rb
module BackpackHelper
end

Week 2/ordenador/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

Week 2/ordenador/app/views/articles/edit.html.erb
<h1 style="color:blue"><u>Edit laptop:</u></h1>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <p>
    <%= f.label :Marca %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Modelo %><br>
    <%= f.text_area :Modelo %>
  </p>

    <p>
    <%= f.label :Procesador %><br>
    <%= f.text_area :Procesador %>
  </p>

    <p>
    <%= f.label :RAM %><br>
    <%= f.text_area :RAM %>
  </p>
<p>
    <%= f.label :Precio %><br>
    <%= f.text_area :Precio %>
  </p>



  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path%>

Week 2/ordenador/app/views/articles/index.html.erb
<h1><u>Online Shop</u></h1>
<h1 style="color:blue">List Of Laptops:</h1> 
<table>
<% @articles.each do |article|%>
    <div><%= article.title %> 
<%= link_to 'Show',  article_path(article)%>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
</table>
<p>
    <%= link_to 'New article', new_article_path %>
</p>


<strong>New!!</strong> - If you want buy Backpacks click <a href="http://localhost:3000/backpacks">Here</A> !!!

Week 2/ordenador/app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label :Marca %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Modelo %><br>
    <%= f.text_area :Modelo %>
  </p>

  <p>
    <%= f.label :Procesador %><br>
    <%= f.text_area :Procesador %>
  </p>

  <p>
    <%= f.label :RAM %><br>
    <%= f.text_area :RAM %>
  </p>

  <p>
    <%= f.label :Precio %><br>
    <%= f.text_area :Precio %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back', articles_path %>
</p>

Week 2/ordenador/app/views/articles/show.html.erb
<h3>
  <strong>Marca:</strong>
  <%= @article.title %>
</h3>

<p>
  <strong>Modelo:</strong>
  <%= @article.Modelo %>
</p>
<p>
  <strong>Procesador:</strong>
  <%= @article.Procesador %>
</p>

<p>
  <strong>RAM:</strong>
  <%= @article.RAM %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @article.Precio %>
</p>

<p>
    <%= link_to 'Edit', edit_article_path(@article)%> |
    <%= link_to 'Back', articles_path%>
</p>

Week 2/ordenador/app/views/backpacks/edit.html.erb
<h1>Edit backpack</h1>

<%= form_for :backpack, url: backpack_path(@backpack), method: :patch do |f| %>
  <p>
    <%= f.label :Marca %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Color %><br>
    <%= f.text_field :Color %>
  </p>

  <p>
    <%= f.label :Capacidad %><br>
    <%= f.text_area :Capacidad %>
  </p>

  <p>
    <%= f.label :Bolsillos %><br>
    <%= f.text_area :Bolsillos %>
  </p>

   <p>
    <%= f.label :Resistente %><br>
    <%= f.text_area :Resistente %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', backpacks_path %>

Week 2/ordenador/app/views/backpacks/index.html.erb
 <h1>List Of Backpacks</h1>
<% @backpacks.each do |backpack|%>
<div><%= backpack.title %><%= link_to 'Show',  backpack_path(backpack)%>
<%= link_to 'Edit', edit_backpack_path(backpack) %>
<%= link_to 'Destroy', backpack_path(backpack), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

<p>
    <%= link_to 'New backpack', new_backpack_path %>
</p>


If you want buy a Laptop click <a href="http://localhost:3000/articles">Here</A> !!!

Week 2/ordenador/app/views/backpacks/new.html.erb
<%= form_for @backpack do |f| %>
  <p>
    <%= f.label :Marca %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Color %><br>
    <%= f.text_area :Color %>
  </p>

  <p>
    <%= f.label :Capacidad %><br>
    <%= f.text_area :Capacidad %>
  </p>

  <p>
    <%= f.label :Bolsillos %><br>
    <%= f.text_area :Bolsillos %>
  </p>

  <p>
    <%= f.label :Resistente %><br>
    <%= f.text_area :Resistente %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to 'Back', backpacks_path %>
</p>

Week 2/ordenador/app/views/backpacks/show.html.erb
<h3>
  <strong>Marca</strong>
  <%= @backpack.title %>
</h3>

<p>
  <strong>Color</strong>
  <%= @backpack.Color %>
</p>

<p>
  <strong>Capacidad</strong>
  <%= @backpack.Capacidad %>
</p>

<p>
  <strong>Bolsillos</strong>
  <%= @backpack.Bolsillos %>
</p>

<p>
  <strong>Resistente</strong>
  <%= @backpack.Resistente %>
</p>
<p>
<%= link_to 'Edit', edit_backpack_path(@backpack)%> |
<%= link_to 'Back', backpacks_path %>
</p>

Week 2/ordenador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ordenador</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>